### Navie Bayes

### Stage 1: Training
-- Navie Bayes create a look up table ( It will stire all the probabilities)

### Stage 2: Testing

In [67]:
import numpy as np
import pandas as pd

In [68]:
df = pd.read_csv('../data/play_tennis.csv')
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [69]:
df.iloc[0]

day            D1
outlook     Sunny
temp          Hot
humidity     High
wind         Weak
play           No
Name: 0, dtype: str

In [70]:
df.drop(columns='day',inplace=True)

In [71]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

### Problem 1

#### outlook=Sunny	temp=Hot	humidity=High	wind=Weak	

#### Play or No Play


### Solution

#### P(Yes | Sunny, Hot, High , Weak ) = P (Sunny | Yes) * P (Hot | Yes) * P (High | Yes) * P (Weak | Yes) * P(Yes)

#### P(No | Sunny, Hot, High , Weak ) = P (Sunny | No) * P (Hot | No) * P (High | No) * P (Weak | No) * P(No)


#### Compare and decide using the maximum a posteriori rule

### Problem 2

#### outlook=Overcast	temp=Cold	humidity=Low	wind=Weak	

#### Play or No Play


### Solution

#### P(Yes | Overcast, Cold, Low , Weak ) = P (Overcast | Yes) * P (Cold | Yes) * P (Low | Yes) * P (Weak | Yes) * P(Yes)

#### P(No | Overcast, Cold, Low , Weak ) = P (Overcast | No) * P (Cold | No) * P (Low | No) * P (Weak | No) * P(No)


#### Compare and decide using the maximum a posteriori rule

In [72]:
df['outlook'].value_counts()

outlook
Sunny       5
Rain        5
Overcast    4
Name: count, dtype: int64

In [73]:
df['temp'].value_counts()

temp
Mild    6
Hot     4
Cool    4
Name: count, dtype: int64

In [74]:
df['humidity'].value_counts()

humidity
High      7
Normal    7
Name: count, dtype: int64

In [75]:
df['wind'].value_counts()

wind
Weak      8
Strong    6
Name: count, dtype: int64

### P(Yes)
### P(No)

In [76]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [77]:
probability_yes = 9/14

In [78]:
probability_yes

0.6428571428571429

In [79]:
probability_no = 5/ 14

In [80]:
probability_no

0.35714285714285715

#### Probability of each column wrt yes and no

#### Outlook

In [81]:
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [82]:
p_overcast_no = 0
p_rain_no = 2 / 5
p_sunny_no = 3 / 5


p_overcast_yes = 4 / 9
p_rain_yes = 3 / 9
p_sunny_yes = 2 / 9

#### temp

In [83]:
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [84]:
p_cool_no = 1 / 5
p_hot_no = 2 / 5
p_mild_no = 2 / 5


p_cool_yes = 3 / 9
p_hot_yes = 2 / 9
p_mild_yes = 2 / 9

#### humidity

In [85]:
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [86]:
p_high_no = 4 / 5
p_normal_no = 1 / 5

p_high_yes = 3 / 9
p_normal_yes = 6 / 9

#### wind

In [87]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [88]:
p_strong_no = 3 / 5
p_weak_no = 2 / 5

p_strong_yes = 3 / 9
p_weak_yes = 6 / 9

#### Problem 1

outlook=Sunny temp=Hot humidity=High wind=Weak

In [92]:
probability_yes_result = p_sunny_yes * p_hot_yes * p_high_yes * p_weak_yes * probability_yes
probability_yes_result

0.007054673721340387

In [94]:
probability_no_result = p_sunny_no * p_hot_no * p_high_no * p_weak_no * probability_no
probability_no_result

0.02742857142857143

## Result - Play NO